import React, { useState } from 'react';
import { 
  CheckCircle2, 
  Circle, 
  Sparkles, 
  Printer, 
  Download, 
  ExternalLink, 
  Clock, 
  ArrowRight, 
  MessageSquareHeart, 
  GraduationCap, 
  Map, 
  BookOpen, 
  Layers, 
  Award,
  ChevronDown
} from 'lucide-react';
import { CareerRecommendation, RoadmapStep } from '../types';

interface RoadmapViewProps {
  career: CareerRecommendation;
  allCareers?: CareerRecommendation[];
  onSelectCareer?: (career: CareerRecommendation) => void;
  onOpenMentor: (career: CareerRecommendation, contextTopic?: string) => void;
  completedStepIds: string[];
  onToggleStepCompleted: (stepId: string) => void;
}

const STAGE_COLORS: Record<string, { bg: string; text: string; border: string; badge: string }> = {
  Foundation: { bg: 'bg-[#2D4534]', text: 'text-[#2D4534]', border: 'border-[#2D4534]', badge: 'bg-[#EBF2ED] text-[#2D4534] dark:bg-[#202E24] dark:text-[#B5D6BE]' },
  Skills: { bg: 'bg-[#4A6550]', text: 'text-[#4A6550]', border: 'border-[#4A6550]', badge: 'bg-[#EBF2ED] text-[#2D4534] dark:bg-[#202E24] dark:text-[#B5D6BE]' },
  Projects: { bg: 'bg-[#B88448]', text: 'text-[#B88448]', border: 'border-[#B88448]', badge: 'bg-[#FAF0E1] text-[#8C5D1F] dark:bg-[#332515] dark:text-[#E8C28D]' },
  Education: { bg: 'bg-[#516F7D]', text: 'text-[#516F7D]', border: 'border-[#516F7D]', badge: 'bg-[#EBF1F5] text-[#2C4B5E] dark:bg-[#1E2B33] dark:text-[#9EC4D7]' },
  Experience: { bg: 'bg-[#C87D55]', text: 'text-[#C87D55]', border: 'border-[#C87D55]', badge: 'bg-[#FAF0EB] text-[#A64E24] dark:bg-[#331C14] dark:text-[#E8A584]' },
  Career: { bg: 'bg-[#3D3A35]', text: 'text-[#3D3A35]', border: 'border-[#3D3A35]', badge: 'bg-[#EFEAE1] text-[#3D3A35] dark:bg-[#2F2C29] dark:text-[#D5D0C7]' },
};

export const RoadmapView: React.FC<RoadmapViewProps> = ({
  career,
  allCareers = [],
  onSelectCareer,
  onOpenMentor,
  completedStepIds,
  onToggleStepCompleted,
}) => {
  const [activeStageFilter, setActiveStageFilter] = useState<string>('all');
  const [showCareerDropdown, setShowCareerDropdown] = useState<boolean>(false);

  const stages = [
    { name: 'Foundation', num: 1 },
    { name: 'Skills', num: 2 },
    { name: 'Projects', num: 3 },
    { name: 'Education', num: 4 },
    { name: 'Experience', num: 5 },
    { name: 'Career', num: 6 },
  ];

  const filteredSteps = career.roadmap.filter((step) => {
    if (activeStageFilter === 'all') return true;
    return step.stage.toLowerCase() === activeStageFilter.toLowerCase();
  });

  const totalActions = career.roadmap.reduce((acc, step) => acc + step.keyActions.length, 0);
  const completedActionsCount = career.roadmap.reduce((acc, step) => {
    return acc + step.keyActions.filter((_, idx) => completedStepIds.includes(`${step.id}-action-${idx}`)).length;
  }, 0);

  const progressPercent = totalActions > 0 ? Math.round((completedActionsCount / totalActions) * 100) : 0;

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadSummary = () => {
    const summaryText = `PATHPILOT AI - STUDENT LEARNING & CAREER ROADMAP
=====================================================
Target Career (Suggestion): ${career.name} (${career.category})
Interest Match: ${career.matchScore}%
Tagline: ${career.tagline}

IMPORTANT NOTICE:
PathPilot AI is an educational exploration tool. All career recommendations, match scores, and roadmaps are suggestions to inspire curiosity and learning—never guarantees, fixed predictions, or directives. Discuss all educational plans with your school counselor, teachers, and parents/guardians.

Why It Matches You:
${career.whyItMatches}

SIX-STAGE ROADMAP:
-----------------------------------------------------
${career.roadmap
  .map(
    (step) => `
[STAGE ${step.stageNumber}: ${step.stage.toUpperCase()}] - ${step.title} (${step.estimatedDuration})
Summary: ${step.description}
Key Milestones:
${step.keyActions.map((a, i) => `  [ ] ${a}`).join('\n')}
Recommended Resources:
${step.recommendedResources.map((r) => `  • ${r.name} (${r.type}): ${r.note}`).join('\n')}
`
  )
  .join('\n')}

COUNSELOR & PARENT DISCUSSION QUESTIONS:
-----------------------------------------------------
${career.discussionPointsForCounselor.map((q) => `• ${q}`).join('\n')}

Generated by PathPilot AI - Educational Guidance & Career Exploration Platform
*Reminder: Discuss your academic choices with school counselors and parents.
`;

    const blob = new Blob([summaryText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PathPilot-Roadmap-${career.name.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 space-y-8 print:p-0 print:m-0">
      {/* Top Header Card */}
      <div className="bg-white dark:bg-[#262422] border border-[#E8E2D9] dark:border-[#383531] rounded-3xl p-6 sm:p-8 shadow-xs">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="px-3 py-0.5 rounded-full bg-[#EBF2ED] dark:bg-[#202E24] text-[#2D4534] dark:text-[#B5D6BE] text-xs font-extrabold flex items-center gap-1">
                <Sparkles className="w-3 h-3 text-[#4A6550]" />
                <span>6-Stage Visual Roadmap</span>
              </span>
              <span className="text-xs text-[#736E65] dark:text-[#A39E93] font-medium">Foundation to Career</span>
            </div>

            <div className="relative inline-block">
              {allCareers.length > 1 ? (
                <div className="flex items-center gap-2">
                  <button
                    id="roadmap-career-dropdown-btn"
                    onClick={() => setShowCareerDropdown(!showCareerDropdown)}
                    className="text-2xl sm:text-3xl font-bold font-display text-[#3D3A35] dark:text-[#FDFBF7] flex items-center gap-2 hover:text-[#4A6550] dark:hover:text-[#7D9D85] transition-colors text-left cursor-pointer"
                  >
                    <span>{career.name}</span>
                    <ChevronDown className="w-5 h-5 text-[#8C867A]" />
                  </button>

                  {showCareerDropdown && (
                    <div className="absolute left-0 top-full mt-2 w-72 bg-white dark:bg-[#262422] border border-[#E8E2D9] dark:border-[#383531] rounded-2xl shadow-xl z-30 p-2 space-y-1">
                      <div className="text-[10px] font-bold text-[#8C867A] uppercase tracking-wider px-2 py-1">
                        Switch Career Roadmap
                      </div>
                      {allCareers.map((c) => (
                        <button
                          key={c.id}
                          onClick={() => {
                            if (onSelectCareer) onSelectCareer(c);
                            setShowCareerDropdown(false);
                          }}
                          className={`w-full text-left px-3 py-2 rounded-xl text-xs font-semibold flex items-center justify-between cursor-pointer ${
                            c.id === career.id
                              ? 'bg-[#EBF2ED] dark:bg-[#202E24] text-[#2D4534] dark:text-[#B5D6BE]'
                              : 'text-[#5C574F] dark:text-[#D5D0C7] hover:bg-[#FAF8F5] dark:hover:bg-[#2F2C29]'
                          }`}
                        >
                          <span>{c.name}</span>
                          <span className="text-[10px] opacity-70">{c.matchScore}%</span>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              ) : (
                <h1 className="text-2xl sm:text-3xl font-bold font-display text-[#3D3A35] dark:text-[#FDFBF7]">
                  {career.name}
                </h1>
              )}
            </div>

            <p className="text-xs sm:text-sm text-[#736E65] dark:text-[#A39E93] mt-1 max-w-xl">
              {career.tagline}
            </p>
          </div>

          {/* Export & Actions */}
          <div className="flex flex-wrap items-center gap-2 shrink-0 print:hidden">
            <button
              id="roadmap-print-btn"
              onClick={handlePrint}
              className="px-3.5 py-2 rounded-xl border border-[#DFD7CB] dark:border-[#383531] hover:bg-[#FAF8F5] dark:hover:bg-[#2F2C29] text-[#5C574F] dark:text-[#D5D0C7] text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <Printer className="w-4 h-4" />
              <span>Print</span>
            </button>
            <button
              id="roadmap-download-btn"
              onClick={handleDownloadSummary}
              className="px-3.5 py-2 rounded-xl border border-[#DFD7CB] dark:border-[#383531] hover:bg-[#FAF8F5] dark:hover:bg-[#2F2C29] text-[#5C574F] dark:text-[#D5D0C7] text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download Text</span>
            </button>
            <button
              id="roadmap-ask-mentor-btn"
              onClick={() => onOpenMentor(career, 'Roadmap Stages')}
              className="px-4 py-2 rounded-xl bg-[#B88448] hover:bg-[#9E6E37] text-white text-xs font-bold flex items-center gap-1.5 transition-all shadow-xs cursor-pointer"
            >
              <MessageSquareHeart className="w-4 h-4" />
              <span>Mentor Advice</span>
            </button>
          </div>
        </div>

        {/* Milestone Progress Bar */}
        <div className="mt-6 pt-5 border-t border-[#E8E2D9] dark:border-[#383531]">
          <div className="flex items-center justify-between text-xs mb-2">
            <span className="font-semibold text-[#5C574F] dark:text-[#D5D0C7] flex items-center gap-1.5">
              <Award className="w-4 h-4 text-[#4A6550]" />
              <span>Your Action Milestones Progress:</span>
            </span>
            <span className="font-bold text-[#2D4534] dark:text-[#B5D6BE]">
              {completedActionsCount} of {totalActions} completed ({progressPercent}%)
            </span>
          </div>
          <div className="w-full bg-[#EFEAE1] dark:bg-[#2F2C29] h-2.5 rounded-full overflow-hidden">
            <div
              className="bg-gradient-to-r from-[#3A5341] to-[#608269] h-full transition-all duration-300"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>
      </div>

      {/* Visual Roadmap Sequence Bar */}
      <div className="bg-white dark:bg-[#262422] border border-[#E8E2D9] dark:border-[#383531] rounded-3xl p-4 sm:p-6 shadow-xs overflow-x-auto print:hidden">
        <div className="flex items-center justify-between min-w-[650px] gap-2">
          {stages.map((stg, idx) => {
            const isSelected = activeStageFilter === stg.name.toLowerCase();
            const colors = STAGE_COLORS[stg.name] || STAGE_COLORS.Foundation;

            return (
              <React.Fragment key={stg.name}>
                <button
                  id={`roadmap-stage-pill-${stg.name.toLowerCase()}`}
                  onClick={() => setActiveStageFilter(isSelected ? 'all' : stg.name.toLowerCase())}
                  className={`flex flex-col items-center gap-1 p-2.5 rounded-2xl transition-all cursor-pointer flex-1 ${
                    isSelected
                      ? 'bg-[#FAF8F5] dark:bg-[#2F2C29] scale-105 shadow-xs border border-[#DFD7CB] dark:border-[#383531]'
                      : 'hover:bg-[#FAF8F5] dark:hover:bg-[#1F1D1B]'
                  }`}
                >
                  <div
                    className={`w-9 h-9 rounded-xl flex items-center justify-center text-[#FDFBF7] font-bold text-xs shadow-xs ${colors.bg}`}
                  >
                    {stg.num}
                  </div>
                  <span className="text-xs font-bold text-[#3D3A35] dark:text-[#FDFBF7] mt-0.5">
                    {stg.name}
                  </span>
                  <span className="text-[10px] text-[#8C867A]">Stage {stg.num}</span>
                </button>

                {idx < stages.length - 1 && (
                  <ArrowRight className="w-4 h-4 text-[#DFD7CB] dark:text-[#4A4641] shrink-0" />
                )}
              </React.Fragment>
            );
          })}
        </div>

        {activeStageFilter !== 'all' && (
          <div className="mt-3 text-center">
            <button
              onClick={() => setActiveStageFilter('all')}
              className="text-xs text-[#4A6550] dark:text-[#7D9D85] hover:underline font-semibold cursor-pointer"
            >
              Show all 6 stages together
            </button>
          </div>
        )}
      </div>

      {/* Roadmap Steps Detailed Timeline */}
      <div className="space-y-6">
        {filteredSteps.map((step) => {
          const colors = STAGE_COLORS[step.stage] || STAGE_COLORS.Foundation;

          return (
            <div
              key={step.id}
              id={`roadmap-step-card-${step.id}`}
              className="bg-white dark:bg-[#262422] border border-[#E8E2D9] dark:border-[#383531] rounded-3xl p-6 sm:p-8 shadow-xs relative overflow-hidden group hover:border-[#4A6550]/60 transition-all"
            >
              {/* Stage Banner Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4">
                <div className="flex items-center gap-3">
                  <div
                    className={`w-10 h-10 rounded-2xl flex items-center justify-center text-[#FDFBF7] font-extrabold text-sm shadow-xs ${colors.bg}`}
                  >
                    {step.stageNumber}
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-extrabold ${colors.badge}`}>
                        STAGE {step.stageNumber}: {step.stage.toUpperCase()}
                      </span>
                      <span className="text-xs text-[#736E65] flex items-center gap-1">
                        <Clock className="w-3.5 h-3.5" />
                        <span>{step.estimatedDuration}</span>
                      </span>
                    </div>
                    <h3 className="text-lg font-bold font-display text-[#3D3A35] dark:text-[#FDFBF7] mt-1">
                      {step.title}
                    </h3>
                  </div>
                </div>

                <button
                  id={`ask-stage-${step.stageNumber}-btn`}
                  onClick={() => onOpenMentor(career, `Stage ${step.stageNumber} (${step.stage}): ${step.title}`)}
                  className="text-xs font-semibold text-[#736E65] dark:text-[#A39E93] hover:text-[#B88448] dark:hover:text-[#E8C28D] flex items-center gap-1 self-start sm:self-auto print:hidden cursor-pointer"
                >
                  <MessageSquareHeart className="w-3.5 h-3.5 text-[#B88448]" />
                  <span>Ask Mentor about Stage {step.stageNumber}</span>
                </button>
              </div>

              {/* Subtitle & Description */}
              <p className="text-xs sm:text-sm text-[#5C574F] dark:text-[#D5D0C7] leading-relaxed mb-6">
                {step.description}
              </p>

              {/* Key Actions Checklist */}
              <div className="mb-6">
                <h4 className="text-xs font-bold text-[#3D3A35] dark:text-[#FDFBF7] uppercase tracking-wider mb-3">
                  Actionable Milestones:
                </h4>
                <div className="space-y-2.5">
                  {step.keyActions.map((action, idx) => {
                    const actionId = `${step.id}-action-${idx}`;
                    const isChecked = completedStepIds.includes(actionId);

                    return (
                      <div
                        key={idx}
                        id={`milestone-${actionId}`}
                        onClick={() => onToggleStepCompleted(actionId)}
                        className={`p-3.5 rounded-xl border text-xs flex items-start gap-3 cursor-pointer transition-all ${
                          isChecked
                            ? 'bg-[#EBF2ED] dark:bg-[#202E24] border-[#4A6550]/40 text-[#2D4534] dark:text-[#D5EAD9]'
                            : 'bg-[#FAF8F5] dark:bg-[#1F1D1B] border-[#E8E2D9] dark:border-[#383531] text-[#5C574F] dark:text-[#D5D0C7] hover:bg-[#EFEAE1] dark:hover:bg-[#2F2C29]'
                        }`}
                      >
                        <button
                          type="button"
                          className="mt-0.5 shrink-0 text-[#4A6550] dark:text-[#7D9D85]"
                        >
                          {isChecked ? (
                            <CheckCircle2 className="w-4 h-4 fill-[#4A6550] text-[#FDFBF7] dark:fill-[#7D9D85]" />
                          ) : (
                            <Circle className="w-4 h-4 text-[#8C867A]" />
                          )}
                        </button>
                        <span className={`leading-relaxed ${isChecked ? 'line-through opacity-70' : ''}`}>
                          {action}
                        </span>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Recommended Resources Box */}
              {step.recommendedResources && step.recommendedResources.length > 0 && (
                <div className="p-4 rounded-2xl bg-[#FAF8F5] dark:bg-[#1F1D1B] border border-[#E8E2D9] dark:border-[#383531]">
                  <div className="flex items-center gap-1.5 text-xs font-bold text-[#3D3A35] dark:text-[#FDFBF7] mb-2">
                    <BookOpen className="w-3.5 h-3.5 text-[#516F7D]" />
                    <span>Free & Low-Cost Learning Resources:</span>
                  </div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {step.recommendedResources.map((res, idx) => (
                      <div
                        key={idx}
                        className="p-2.5 rounded-xl bg-white dark:bg-[#262422] border border-[#E8E2D9] dark:border-[#383531] text-xs flex flex-col justify-between"
                      >
                        <div>
                          <span className="font-bold text-[#3D3A35] dark:text-[#EFECE6] block">
                            {res.name}
                          </span>
                          <span className="text-[11px] text-[#736E65] dark:text-[#A39E93] mt-0.5 block">
                            {res.note}
                          </span>
                        </div>
                        <span className="text-[10px] font-semibold text-[#2D4534] dark:text-[#B5D6BE] capitalize mt-2 self-start bg-[#EBF2ED] dark:bg-[#202E24] px-2 py-0.5 rounded">
                          {res.type.replace('_', ' ')}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
